const exchange = {
  id: 'ripple',
  name: 'Ripple dEX',
  countries: ['US'],
  urls: {
    api: '',
    www: '',
    doc: '',
  },
  version: '',
  api: {},
  has: {
    CORS: false,
    publicAPI: true,
    privateAPI: true,
    cancelOrder: true,
    createDepositAddress: true,
    createOrder: true,
    fetchBalance: true,
    fetchCanceledOrders: true,
    fetchClosedOrder: true,
    fetchClosedOrders: true,
    fetchCurrencies: true,
    fetchDepositAddress: true,
    fetchMarkets: true,
    fetchMyTrades: true,
    fetchOHLCV: false,
    fetchOpenOrder: true,
    fetchOpenOrders: true,
    fetchOrder: true,
    fetchOrderBook: true,
    fetchOrders: true,
    fetchStatus: 'emulated',
    fetchTicker: true,
    fetchTickers: true,
    fetchBidsAsks: false,
    fetchTrades: true,
    withdraw: true,
  },
  timeout: undefined,
  rateLimit: undefined,
  userAgent: '',
  verbose: false,
  markets: {},
  symbols: [],
  currencies: {},
  markets_by_id: {},
  currencies_by_id: {},
};

export default exchange;
